import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export const fontSans = localFont({
  src: '../assets/fonts/Inter.ttf',
  variable: '--font-sans'
})

const fontHeading = localFont({
  src: '../assets/fonts/CalSans-SemiBold.woff2',
  variable: '--font-heading'
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en" className="dark">
      <body className={cn(
          'relative h-full w-full bg-slate-950',
          fontSans.variable,
          fontHeading.variable
        )}>
          <div className="rounded-full bg-[radial-gradient(circle_farthest-side,rgba(255,0,182,.15),rgba(255,255,255,0))]">
        <ThemeProvider>
        {children}
        </ThemeProvider>
    </div>
    
      </body>
    </html>
  );
}
